version: '3.8'

services:
    database:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD} # Set in .env file
            POSTGRES_DB: ${DB_NAME} # Set in .env file
            POSTGRES_USER: ${DB_USERNAME} # Set in .env file
        volumes:
            - db_data:/var/lib/postgresql/data

    backend:
        build: ./tools/devcontainer
        volumes:
            - ${PWD}/backend:/app
        ports:
            - 8080:3000
        command: /entrypoint.sh npm run start:dev
        env_file:
            - .env

    frontend:
        build: ./tools/devcontainer
        volumes:
            - ${PWD}/frontend:/app
        ports:
            - 80:5000
        command: /entrypoint.sh npm run dev

volumes:
    db_data:
