version: '3.8'

services:
    database:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD} # Set in .env file
            POSTGRES_DB: ${DB_NAME} # Set in .env file
            POSTGRES_USER: ${DB_USERNAME} # Set in .env file
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]

    backend:
        build: ./backend
        depends_on: ['database']
        ports:
            - 8080:3000
        env_file:
            - .env

    frontend:
        build:
          context: ./frontend
          args:
            - VITE_PAYPAL_CLIENT_ID
            - VITE_DOMAIN
        depends_on: ['backend']
        ports:
            - 80:80

volumes:
    db_data:
