<script setup lang="ts"></script>

<template>
  <main>
    <h1>ERROR 404: PAGE NOT FOUND</h1>
    <marquee
      >oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooooooooooooooooddoooodddddoooooooooooooooooooooooooooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooooooooooooooooolc:;,,''''',,,;;:ccloodoooooooooooooooooooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooooooooooodoc;,,,,,;;:coolcc:;;;,,,,,,,:odooooooooooooooooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooooc;,',;coddxxxddddddddddxxxddolc;,;codoooooooooooooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooo:,,,;cldddddddddollllllllllllooodddo:,,;cooooooooooooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooool,'cdxxddddddollllllllllllooooolllloodddl:,,;coooooooooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooo:',dxxxxxddollllooooooooooooooooooolllllooddl;,,;looooooooooooooooo</marquee
    >
    <marquee
      >oooooooooodl,'cdxxddddolloooooooooooooooooooooooooollllooddoc;',looooooooooooooo</marquee
    >
    <marquee
      >ooooooooooc',oxxdddodoooooooooooooooooooooooooooooooooooooooodc.'ldooooooooooooo</marquee
    >
    <marquee
      >oooooooood:.cxddoooooooooddoolllllllllllllllloooooooooooooooooo:.,oooooooooooooo</marquee
    >
    <marquee
      >oooooooood:.;xdooooolccc::cccccccccccccc::::::::::;coooooooooooo;.;ooooooooooooo</marquee
    >
    <marquee
      >oooooooood:.;xdoc;:ccloodxkOOOOOOOOOOOOOOkkOkkkxxdc,cdoodoooooooo;.;oooooooooooo</marquee
    >
    <marquee
      >oooooooood:.,do:,cx00000OOOOOOOOOOOOOOOOOOOOOOOOOkx:,ododooooooooo,.:doooooooooo</marquee
    >
    <marquee
      >oooooooood,.:d:ck00K00000OOOOOOOOOOOOOOOOOOOOO0000k:;oddddooooooool'.cdooooooooo</marquee
    >
    <marquee
      >oooooooooo'.c::0XKKK000OOOOOOOOOOOOOOOOOOOOOOOO000koodddddddooooood:.,oooooooooo</marquee
    >
    <marquee
      >oooooooooo'.;:xNKKKK0000OOOOOOOOOOOOOOOOOOOOOOOOOOxddxdddddddoooood:.,oooooooooo</marquee
    >
    <marquee
      >oooooooooo,
      .lKXXKKKK000OOOO00000OOOOOOOOOOOOOOOOkxdddddddddddoooodc.'oooooooooo</marquee
    >
    <marquee
      >oooooooooo,
      'kKXKKKK00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkddddddddddooodl..ldoooooooo</marquee
    >
    <marquee
      >oooooooood;.:OK0kxxddxkkkkkkkkkkxoccccccccldkkOOOOOOOOkxdddddddddodl..ldoooooooo</marquee
    >
    <marquee
      >oooooooood:.:0Oo:;,,,;:oxxxkkxxo:,',;,;;;;:lddxxkOOOOOOOkooddddddddl.'odoooooooo</marquee
    >
    <marquee
      >oooooooood:.,c::c::;,'';oxxkkxxl'';:c;,''..';;:loxkOOOOOOxodddddddd;.;dooooooooo</marquee
    >
    <marquee
      >ooooooooodl..cdo::c,. ..;:clll:''looc:, .
      ..;;.':::ccllodoloddddddl.'odooooooooo</marquee
    >
    <marquee
      >oooooooooxl'lOkocoo' . ,''lddo;.cxddddc.. ..:o;,dxddoolllc:;:;;::c'
      .coooooooooo</marquee
    >
    <marquee
      >oooooooooo,;kOOkkkdc:;co;'x0OOc'lxdddddoooodxxc'oOkOOOOO00xooolc,.''..ldoooooooo</marquee
    >
    <marquee
      >oooooooooo';OK00OOkxxxxk;.o0OOx:,cxxxxxxxxxxko,:kOOOOOOOOOxloddxddxx:.;doooooooo</marquee
    >
    <marquee
      >ooooooooool,;kK0000OO0Ol.:O0OOOko,;oxkOOOOOkl,ckOOO0OOOOOOxdxkkddxkko..ldooooooo</marquee
    >
    <marquee
      >oooooooooodl..ldxkOkdl:''xKOOOkkkd::::cccccccokOO0O0OOOOOkkkkOOxddkkc.,ooooooooo</marquee
    >
    <marquee
      >oooooooooooo'.:ollllclo:dK0OOOOkkkddddolcldkkkkOOOOOOOOkkkkkOkxxxxko.'ldoooooooo</marquee
    >
    <marquee
      >oooooooooood;.oK000OOkl;oxkkxdolokl;oxxxxxxxxkkkkkkkkkkkkxxxkdlkOOx'.ldooooooooo</marquee
    >
    <marquee
      >ooooooooooodc.l00OOOOkxdlldddl::ldddxkxxxxxxxxxxxkkkkkkkxxxkxldOOk;.cdoooooooooo</marquee
    >
    <marquee
      >ooooooooooodo,:O0OOOOkkOkkxddddddxxxxxxxxxxxxxxxxxxxxxxxxxxo:,:dd;.:oooooooooooo</marquee
    >
    <marquee
      >ooooooooooood:,dOOOOkxxxxxxdddddddddxddddddxxxxxxxxxxxxxxxxllo'.':looooooooooooo</marquee
    >
    <marquee
      >oooooooooooodl';kOOkxdddddddddddoollc:;::lodxxxxxxxxxxxxxxxxxd'.ldoooooooooooooo</marquee
    >
    <marquee
      >oooooooooooood:.lkkkxo:cllc:::::;;;::ccccldddxxddddxxxxxxdxxxc.;oooooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooooo;,lxkkddkOOkkxxxdddxxxxxxxxxddxxddddddddddddxkc.;oooooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooooooc;;lxxxkOOkxxxddddxxxxxxxxdddddddddddddddddxkx,.cdoooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooo:',oxxkOOOkkxxxxxxxkxxxdddddddoccoddddddxkkko.'ooooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooool;';okOOOkkxxxxxxxxxdddddddl;,;codddddxxkkkk:.:dooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooooool,':oxkxxxdddddddddddoc;;,;coddddddxxxkkkOx,.cooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooooooooc'..,,;::;;;;;::;;,;;:codddddddxxxxxkkkkko;:ooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooooooooooooodo'.:c;;;;;;;::cccloddodddddddxxxxxxkkxxxxdoooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooooooooodc.,kOkxddooooooooodddddddddxxxxxxxxxdddoooooooooooooooo</marquee
    >
    <marquee
      >oooooooooooooooooooooooooo,.lOOOkddddddddddddddddddxxxxxxxdddooooooooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooooooooooooooool.'xOkkkxxdddddddddddddddxxxxdddoooooooooooooooooooooo</marquee
    >
    <marquee
      >ooooooooooooooooooooooooooo;.cOkkkkxdddddddddddddddddddooooooooooooooooooooooooo</marquee
    >
  </main>
</template>

<style scoped>
marquee {
  font-family: monospace;
}
</style>
